#!/usr/bin/bash
#
# Run mypy checker
# run from "src" dir

mod=dmarc_rpt

PYTHONPATH=. pylint src/$mod/*.py src/$mod/*/*.py
PYTHONPATH=. pycodestyle --max-line-length=110 src/$mod/*.py src/$mod/*/*.py

PYTHONPATH=. mypy --check-untyped-defs --follow-untyped-imports src/$mod

