#!/usr/bin/bash
#
# Run mypy checker
# run from "src" dir

mod="src/dmarc_rpt"
export PYTHONPATH=$(/usr/bin/realpath ./src)

/usr/bin/pylint $mod/*.py $mod/*/*.py
/usr/bin/pycodestyle --max-line-length=110 $mod/*.py $mod/*/*.py
/usr/bin/mypy --check-untyped-defs --follow-untyped-imports $mod

